[project]
name = "tts-llm-stt-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pydub>=0.25.1",
    "pyttsx3>=2.99",
    "requests>=2.32.5",
    "speechrecognition>=3.14.5",
]
